version: '3.8'
services:
    gateway:
        build: ./gateway
        container_name: gateway
        # depends_on: [cache-master]
        tty: true
        volumes: 
            - ./gateway:/gateway
        restart: always
        ports:
            - 7171:7171
        # networks:
        #     - gateway-network

    client-service:
        build: ./client-service
        container_name: client-service
        depends_on: [gateway]
        tty: true
        volumes: 
            - ./client-service:/client-service
        restart: always
        ports:
            - 1234:1234
        # networks:
        #     - gateway-network

# networks:
#     gateway-network:
