version: '3.8'
services:
    gateway:
        build: ./gateway
        container_name: pbl-gateway
        # depends_on: [cache-master]
        tty: true
        volumes: 
            - ./gateway:/gateway
        restart: always
        ports:
            - 7171:7171

    client-service:
        build: ./client-service
        container_name: pbl-client-service
        depends_on: [gateway]
        tty: true
        volumes: 
            - ./client-service:/client-service
        restart: always
        ports:
            - 8080:8080
