version: '3.8'
services:
    gateway:
        build: ./gateway
        container_name: gateway
        tty: true
        restart: always
        ports:
            - 7171:7171

    client-service-replica1:
        build: ./client-service
        container_name: client-service-replica1
        depends_on: [gateway]
        tty: true
        restart: always
        environment:
            - SERVICE_NAME=client-service
            - ADDRESS=client-service-replica1

    client-service-replica2:
        build: ./client-service
        container_name: client-service-replica2
        depends_on: [gateway]
        tty: true
        restart: always
        environment:
            - SERVICE_NAME=client-service
            - ADDRESS=client-service-replica2

